### ISSUE TITLE
VR Display Issue Reported on Twitter

### ISSUE THREAD

**Issue by roice3** [mtwoodard/hypVR-Ray#25] opened 2018-05-01 18:39 UTC
Hamish Todd having some trouble with the display. He writes:

"it's responding to orientation change but not displaying in headset, both for firefox nightly and chromium"

https://twitter.com/hamish_todd/status/991372931367342080

**Comment by mtwoodard** [comment] 2018-05-21 18:58
I'll be picking up the headset and laptop today so I'll be able to check this out soon.

**Comment by mtwoodard** [comment] 2018-05-24 21:32
So I was able get the Vive up and running on the new laptop and I noticed that the stereoscopy seems to change based on the rotation of the HMD. Looking at a distant object I noticed that rotating my head clockwise brought the two images closer together and vice versa. I'm uncertain of what could causing the issue, my gut tells me it is something to do with how we rotate our eyes. I plan on looking more into this tomorrow in order to nail down the cause of the problem

**Comment by henryseg** [comment] 2018-05-25 14:05
I tried it myself on a Vive Pro at the friend's house I'm visiting now. We noticed that facing the blue light we could get the image to converge, but looking towards the red the eyes are the wrong way round. I think there's likely some matrix getting multiplied the wrong way round, or it should be the inverse of the matrix.

**Comment by roice3** [comment] 2018-05-25 14:18
Note also that motion for the Euclidean honeycomb is off (even when not viewing stereoscopically), and I haven't yet tracked the issue down. Something to be aware of while "the patient is on the table" digging into the view matrices.

**Comment by mtwoodard** [comment] 2018-05-26 00:17
So this turned out to be a bit of a can of worms. I was able to fix a few different issues to start, specifically left and right eye translations were swapped and the VR device would not rotate the eyes when starting up. Still the eyes are not quite lining up, when looking at the small light object I noticed the right eye is too far to the right and the left eye is too far to the left. Is there a chance that we need to rewrite the setFromAxisAngle function so that it uses hyperbolic sine functions? Also when we calculate the turningAngle I noticed that we used math.asin, do we need to switch this to math.asinh?

**Comment by mtwoodard** [comment] 2018-05-26 00:30
~~I've noticed that if I set the angle to 0 degrees it does not produce the same result as 360 degrees. Clearly that shouldn't happen.~~ Turns out I had been using degrees where I should have using radians.

**Comment by henryseg** [comment] 2018-05-26 03:33
All the stuff to do with rotation of the headset should be the same whether we are in hyperbolic or euclidean space. The only differences should be in translations. So I don't think it's anything to do with replacing asin to asinh. This is going to be one of those issues for which we actually need to trace through the code and understand what's going on.

**Comment by mtwoodard** [comment] 2018-05-31 21:09
I think I've figured out what is causing the movement issue. The position that we are getting from the headset is global to the room you are standing in. So if say I am looking forward down the z axis and move forward, the z position will increase. If you then rotate to the right and move forward the x position will increase. We want it so that which ever direction you are facing it will be the z axis, or at least that's currently how we have it set up.

**Comment by mtwoodard** [comment] 2018-06-10 05:19
I'm going to close this as of now, if more errors occur we can open a new issue.

**Closed as completed by mtwoodard** 2018-06-10 05:19 UTC
